services:
  db:
    image: mysql:9.3
    restart: always
    container_name: lugares_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: lugares
    volumes:
      - "./db:/var/lib/mysql:Z"
